### ISSUE TITLE
2kki: Wedding Cake Badge Unlocked w/ Virtual Mapper

### ISSUE THREAD

**Issue by ElTipejoLoco** [ynoproject/ynobadges#423]
Yeah, I read the past PRs, and I'm sorry to say the Wedding Cake badge might still technically be broken: I obtained the notification for the badge unlocking alongside the (correctly) unlocked Virtual Mapper badge in the map room.

While I had been buying from vending machines prior to entry, at no point in time did I see the Wedding Cake amongst the food and drink spawned, and I don't think the delay between the last vending machine and interacting with the NPC in the map room of the Virtual City was short enough for it to be related, but I could be wrong about that.

In fact, looking at qxy's *V_Earth map event: Its comments claim they use variable 67 for the Y axis of their virtual map there (`V[0067]   : 移動量 Y`). So that's probably the cause, even though scouring through the events I can't see where the variable gets used beyond being reset to 0 at the end... Anyway, if it IS the cause, my proposed solutions would be, from simplest to most painful sounding in my own opinion:
- Tying it to the game ~~flipping the switch~~ manipulating variable 4286 for the Snack Gallery's unlock instead (would punish players who have already unlocked the wedding cake in their save files until they make new ones, I guess); If the Wedding Cake's been consumed by the player, this variable in question should be `32768` or higher (highest should be `524287`), with the only valid values being ones that, when divided by `2^16`, will not return 0 when run through the modal `%= 2` operation in the Snack Gallery's relevant map event
- Figuring out a way for EasyRPG to expose when it's running common events and tie the related badge(s) to Common Event 6 (i.e.- `自販機EV`) only, if that's not already a thing
Unfortunately, the map that the virtual map is in contains a vending machine somewhere (it's one of those 'multiple rooms on a single map' ones), so the idea of just excluding areas without vending machines doesn't work unless a specific exclusion for the region the virtual mapper NPC is in is made, which sounds like a pain personally and would also not prevent the issue from happening any time any other map event comes along and decides to use variable 67. But since that's something that's been done via YNOLocations' repo, it's a possibility. If it helps, exclude the following region inside map 1899: `"coords": { "x1": 47, "y1": 41, "x2": 51, "y2": 43 }` from being valid for the wedding cake and similar future food based badge unlocks, maybe.

Edit: Just wanted to specify this happened and was written with 0.120d Patch 5 in mind, in case anything's changed since.

**Comment by Mimigris** [comment]
- Your second solution would just be an half workaround that wouldn't solve entirely the issue: the issue with the variable 67 is that it is temporary altered just after getting a snack, leading into false positives also when getting some other snacks (e.g. snack 112). It means that if we want to fix the issue, the variable 67 cannot be relied on at all (excluding maps wouldn't work since this issue also affects all snacks vending machines).
- Your first solution would be complex too since we don't have modulo operators to track badges, that it would need to implement it for only one badge and that it would punish players already having completed their Snack Gallery without having the badge, something that should not happen for a badge.
- What would probably make more sense to avoid conflicts would be to allow tracking battle animations (this would need to be implemented), similar to how pictures can be tracked for badges: this way, if the wedding cake animation is shown on-screen, the badge is triggered, and it shouldn't be possible to cause conflicts since this animation is only used for that.

**Comment by ElTipejoLoco** [comment]
The issue wasn't caused _by_ snack vending machines, but rather by a completely different event co-opting the variable for its own purposes. You'd know I already said this if you'd read what I wrote. As a result, excluding a _region_ that contains a room with an event that co-opts the snack variable on this one map would work, but it would still be a single exception for essentially only one badge at present: As far as I know there's only two badges that track snacks in 2kki, and one of them is specific to Virtual City anyway (pizza from karaoke bar, I believe), and the global wedding cake one. I haven't meticulously checked every version after 0.120d Patch 5 to see if it's the only event game-wide that tries using variable 67 for something other than vending machine RNG.
Choosing to implement battle animation tracking would work, and I'd already seen you suggested that in the Discord somewhere between the months I last edited the original post in this and your post. And I agree that that'll work, I don't have a horse in this race.
Thanks for eventually looking at the issue tracker, I guess.

**Comment by ElTipejoLoco** [comment]
Reopening as requested by @Mimigris for archival and/or future purposes.
